import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Lottie from "react-lottie";

import animationData from "../src/lottie/natural-landing-page.json";

import logo from "../public/CapstoneLogo.png";
import Link from "next/link";

export default function Home() {
  // const [data, setData] = useState([]);
  // const [isLoading, setLoading] = useState(false);
  const [windowH, setWindowH] = useState(window.innerHeight);
  const [windowW, setWindowW] = useState(window.innerWidth);

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  const updateDimensions = () => {
    setWindowW(window.innerWidth);
    setWindowH(window.innerHeight);
  };
  useEffect(() => {
    window.addEventListener("resize", updateDimensions);
    return () => window.removeEventListener("resize", updateDimensions);
  }, []);
  // useEffect(() => {
  //   fetch("http://localhost:3600/students", {
  //     method: "GET",
  //     headers: {
  //       "Content-Type": "application/json",
  //       Accept: "application/json",
  //     },
  //   })
  //     .then((res) => res.json())
  //     .then((_data) => {
  //       setData(_data);
  //       console.log(_data);
  //       setLoading(false);
  //     });
  //   setLoading(true);
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {data.map(({ firstName, lastName, enrolmentStatus }) => (
          <>
            hi {firstName} {lastName} your status is {enrolmentStatus}
          </>
        ))} */}

      <Lottie options={defaultOptions} height={windowH} width={windowW} />
      <div className={styles.landing}>
        <Image width={400} height={400} alt="logo" src={logo} />
        <p className={styles.lead}>
          A friendly platform that will make college enrolment more that just
          simplistic
        </p>
        <div className={styles.btns}>
          <Link href="/login" passHref>
            <button className={styles.btn}>Login as Student</button>
          </Link>
          <Link href="/login" passHref>
            <button className={styles.btn}>Login as Admin Officer</button>
          </Link>
        </div>
      </div>
    </div>
  );
}
