import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Lottie from "react-lottie";
import animationData from "../src/lottie/natural-landing-page.json";
import logo from "../public/CapstoneLogo.png";
import { useRouter } from "next/router";

export default function Home() {
  const [windowH, setWindowH] = useState(null);
  const [windowW, setWindowW] = useState(null);
  const router = useRouter();

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  const updateDimensions = () => {
    setWindowW(window.innerWidth);
    setWindowH(window.innerHeight);
  };
  useEffect(() => {
    window.addEventListener("resize", updateDimensions);
    return () => window.removeEventListener("resize", updateDimensions);
  }, []);

  const loginAsStudent = () => {
    router.push("/login/students");
  };

  const loginAsAdmin = () => {
    router.push("/login/administrator");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {data.map(({ firstName, lastName, enrolmentStatus }) => (
          <>
            hi {firstName} {lastName} your status is {enrolmentStatus}
          </>
        ))} */}

      <Lottie options={defaultOptions} height={windowH} width={windowW} />
      <div className={styles.landing}>
        <Image
          width={400}
          height={400}
          alt="logo"
          src={logo}
          onClick={() => router.push("/")}
        />

        <p className={styles.lead}>
          A friendly platform that will make college enrolment more that just
          simplistic
        </p>
        <div className={styles.btns}>
          <button className={styles.btn} onClick={loginAsStudent}>
            Login as Student
          </button>
          <button className={styles.btn} onClick={loginAsAdmin}>
            Login as Admin Officer
          </button>
        </div>
      </div>
    </div>
  );
}
